[package]
name = "opusfile-sys"
version = "0.1.0"
authors = ["Jameson Ernst"]

description = "Raw FFI bindings for libopusfile"
license = "MIT"

build = "build.rs"
links = "opusfile"


[build-dependencies]
pkg-config = "*"

[dependencies]
libc = "*"

